from fastapi import HTTPException, status, APIRouter
from app.gemini_client import get_azure_response
from app import schemas

# Router that exposes endpoints for interacting with the AI agent
router = APIRouter(
    prefix="/agent",
    tags=['AI Agent 🤖'],
)


@router.post("/ask", status_code=status.HTTP_200_OK ,response_model=schemas.AnswerRequest)
async def ask(req: schemas.QuestionRequest):
    """
    Receive a user's question and return an answer generated by the AI model.
    """
    # Validate that the question is not empty
    if not req.question.strip():
        raise HTTPException(status_code=400, detail="Question is required")

    try:
        return get_azure_response(req.question)

    except Exception:
        # Hide internal errors and return a generic gateway error to the client
        raise HTTPException(status_code=502, detail="AI agent error")